---
#ansible_connection: ssh
#ansible_port: 22
#ansible_user: devel
#ansible_ssh_private_key_file: /home/devel/.ssh/id_rsa
docker_users: 
  - "{{ ansible_user }}"

host_interface_name: "{{ ansible_default_ipv4['interface'] }}"
host_interface_ip: "{{ hostvars[inventory_hostname]['ansible_' + host_interface_name]['ipv4']['address'] }}"
